image: maven:latest

stages:
  - build
  - publish-dev
  - publish-prod

build:
  stage: build
  tags:
    - docker
  only:
    - master
    - develop
    - /^release\/v.+$
    - /^hotfix\/v.+$
    - /^feature\/.+$/
  script:
    - mvn clean compile verify
  artifacts:
    paths:
      - "target/*.jar"
      - "starter-pack-runner-config.json"
    expire_in: 1h

publish-dev:
  stage: publish-dev
  image: docker:stable
  services:
    - docker:dind
  tags:
    - docker
  variables:
    DOCKER_TAG: "latest"
  before_script:
    - mv game-runner-config-qa.json game-runner-config.json
    - docker login -u $challenge_username -p $challenge_password
  script:
    - docker build . -t entelectchallenge/game-runner-qa
    - docker push entelectchallenge/game-runner-qa
  only:
    - develop

publish-prod:
  stage: publish-prod
  image: docker:stable
  services:
    - docker:dind
  tags:
    - docker
  variables:
    DOCKER_TAG: "latest"
  before_script:
    - mv game-runner-config-prod.json game-runner-config.json
    - docker login -u $challenge_username -p $challenge_password
  script:
    - docker build . -t entelectchallenge/game-runner
    - docker push entelectchallenge/game-runner
  only:
    - master



