name: Build Engine and Runner

on:
  push:
    branches:
    - master
    - develop
    tags:
    - '*'
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [1.8, 1.11, 1.14]

    steps:
    - uses: actions/checkout@v2
    
    - name: Maven Cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Cache SBT ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
        
    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}

    - name: Build Reference Bot
      run: mvn clean install
      working-directory: reference-bot/java

    - name: Build Game Engine
      run: sbt assembly
      working-directory: game-engine

    - name: Build Game Runner
      run: mvn clean install
      working-directory: game-runner

    - name: Assemble starter pack
      run: ./makeStarterPack.sh

    - name: Upload artifact
      if: matrix.java_version == 1.8
      uses: actions/upload-artifact@v1.0.0
      with:
        name: starter-pack-${{ matrix.java_version }}
        path: starter-pack
        
  publish: 
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: starter-pack-1.8
        path: starter-pack

    - name: Assemble Release
      run: zip -r starter-pack.zip starter-pack/*

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.5
      with:
        files: starter-pack.zip
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
